#!/usr/bin/env bash
# Remove files generated by the example runs so the tests can be redone from
# scratch. Keeps the example CSVs, reference plots in output/, downloaded
# model weights (*.pt), trained_models/, and all shell scripts.
#
# Usage:  bash clean_examples.sh [-y]
#   -y   delete without asking for confirmation

set -euo pipefail
cd "$(dirname "$0")"

ASSUME_YES=0
[[ "${1:-}" == "-y" ]] && ASSUME_YES=1

# Generated artifacts: timestamped configs, train/eval logs, result and
# prepared-dataset directories.
shopt -s nullglob
targets=(
    config_*.yml
    log_train_*.txt log_eval_*.txt
    warn_train_*.txt warn_eval_*.txt
    result_*/
    set_*/
)

existing=()
for t in "${targets[@]}"; do
    existing+=("$t")
done

if [[ ${#existing[@]} -eq 0 ]]; then
    echo "Nothing to clean."
    exit 0
fi

echo "The following generated files/directories will be removed:"
printf '  %s\n' "${existing[@]}"

if [[ $ASSUME_YES -ne 1 ]]; then
    read -r -p "Proceed? [y/N] " answer
    [[ "$answer" == "y" || "$answer" == "Y" ]] || { echo "Aborted."; exit 1; }
fi

rm -rf -- "${existing[@]}"
echo "Done. Re-run prepare.sh to regenerate the datasets."
