dataset:
  train:
    format: lmdb
    src: set_example_train/train.lmdb
    key_mapping:
      Form: energy
    transforms:
      normalizer:
        energy:
          mean:   0.05
          stdev:  0.40
  val:
    format: lmdb
    src: set_example_train/val.lmdb
    key_mapping:
      Form: energy
  test:
    format: lmdb
    src: set_example_train/test.lmdb
    key_mapping:
      Form: energy
      
evaluation_metrics:
  metrics:
    energy:
    - mae
  primary_metric: energy_mae
# gp_gpus: null
gpus: 1
logger: tensorboard
loss_functions:
- energy:
    coefficient: 10
    fn: mae
model:
  backbone:
    act_type: gate
    cutoff: 6.0
    direct_forces: false
    distance_function: gaussian
    edge_channels:    128
    hidden_channels:  128
    lmax: 3
    max_neighbors: 300
    max_num_elements: 100
    mlp_type: spectral
    mmax: 2
    model: esen_backbone
    norm_type: rms_norm_sh
    num_distance_basis: 32
    num_layers: 5
    otf_graph: true
    regress_forces: false
    regress_stress: false
    sphere_channels: 128
    use_envelope: true
    use_pbc: true
    use_pbc_single: true
  heads:
    energy:
      # module: esen_mlp_efs_head
      module: esen_mlp_energy_head
  name: hydra
  otf_graph: true
  pass_through_head_outputs: true
optim:
  batch_size:      32
  eval_batch_size: 32
  # eval_every: 100
  clip_grad_norm: 100
  ema_decay: 0.999
  lr_initial: 0.0004
  max_epochs:  40
  num_workers: 4
  optimizer: AdamW
  optimizer_params:
    weight_decay: 0.001
  scheduler: LambdaLR
  scheduler_params:
    epochs: 40
    lambda_type: cosine
    lr: 0.0004
    lr_min_factor: 0.1
    warmup_epochs: 10
    warmup_factor: 0.2
outputs:
  energy:
    level: system
    property: energy
trainer: mlip_trainer
